name: "update-exit-nodes"
description: "Update Tor exit nodes"
author: "Wouldnt"

inputs:
  token:
    description: "Github token for Auth"
    required: true
    default: ${{ github.token }}
  branch:
    description: "The name of the branch"
    required: false
    default: "main"
  file:
    description: "The name of the file"
    required: true

outputs:
  sha:
    description: "SHA Hash of the updated file"

runs:
  using: "node12"
  main: "dist/index.js"