name: "update-tor-exits"
description: "Update a file through the github api"
author: "Wouldnt"

inputs:
  token:
    description: "Github token for Auth"
    required: true
    default: ${{ github.token }}
  committer_name:
    description: "Name of the committer"
    required: true
  committer_email:
    description: "Email of the committer"
    required: true
  branch:
    description: "The name of the branch"
    required: false
    default: "main"
  file:
    description: "The name of the file"
    required: true

outputs:
  sha:
    description: "SHA Hash of the updated file"

runs:
  using: "node12"
  main: "dist/index.js"