name: Testing

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wouldnt/tor-list-action@Testing
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
